# Generated by Django 3.1.4 on 2021-01-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(max_length=32)),
                ('nb_user', models.IntegerField()),
                ('lifespan', models.DurationField()),
            ],
        ),
    ]
