# Generated by Django 3.1.4 on 2021-01-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210112_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='nb_users',
        ),
        migrations.AddField(
            model_name='conversation',
            name='creator_pseudo',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
